#!/usr/bin/env ruby 

require "rubygems"
require "bundler/setup"
require "mailman"
require File.dirname(__FILE__) + "/../config/initializers/constants.rb"

ENV["RAILS_ENV"] ||= "test"

Mailman.config.ignore_stdin = true

if ENV["RAILS_ENV"] == 'test'
  Mailman.config.maildir = File.expand_path("../../tmp/test_maildir", __FILE__)
else
  Mailman.config.pop3 = {
    server: 'pop.gmail.com', port: 995, ssl: true, 
    username: GMAIL_ADDRESS,
    password: GMAIL_PASSWORD

  }
  Mailman.config.logger = Logger.new("/tmp/mailman_daemon.log")
  Mailman.config.poll_interval = 10
end

Mailman::Application.run do 
  default do 
    begin
      IncomingEmail.receive_email(message)
      puts "#{message.class.inspect}\n#{message.inspect}"
    rescue Exception => e
      Mailman.logger.error "Exception occurred while receiving message: \n#{message}"
      Mailman.logger.error [e, *e.backtrace].join("\n")
    end
  end 
end 
