#!/usr/bin/env ruby 

require "rubygems"
require "bundler/setup"
require "mailman"


Mailman.config.pop3 = {
  server: 'pop.gmail.com', port: 995, ssl: true, 
  username: ENV['GMAIL_ADDRESS'],
  password: ENV['GMAIL_PASSWORD']

}

Mailman.config.logger = Logger.new("log/mailman.log")
Mailman.config.poll_interval = 10

Mailman::Application.run do 
  default do 
    puts "Receieved: #{message.subject} // #{message.body.decoded}"
  end 
end 